#!/usr/bin/env bash
# Manage my_process with start|stop|restart
case "$1" in
  start)
    /bin/bash ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    if [ -f /var/run/my_process.pid ]; then
      kill "$(cat /var/run/my_process.pid)"
      rm -f /var/run/my_process.pid
      echo "manage_my_process stopped"
    fi
    ;;
  restart)
    if [ -f /var/run/my_process.pid ]; then
      kill "$(cat /var/run/my_process.pid)"
      rm -f /var/run/my_process.pid
    fi
    /bin/bash ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac