#!/usr/bin/env bash
# Display PID and name of bash processes
for pid_dir in /proc/[0-9]*; do
  pid="${pid_dir##*/}"
  # Skip PID 1 and non-readable directories
  if [ "$pid" -eq 1 ] || [ ! -r "$pid_dir/comm" ]; then
    continue
  fi

  name=$(<"$pid_dir/comm")
  if [[ "$name" == bash ]]; then
    echo "$pid $name"
  fi
done